; PetFeeder IoT - Configuracao do Ambiente PlatformIO

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200         ; Baud rate deve casar com Serial.begin(115200)
lib_deps      =
    knolleary/PubSubClient@^2.8             ; Biblioteca MQTT: ^2.8 = qualquer 2.x >= 2.8
    adafruit/Adafruit_VL53L0X               ; Sensor ToF VL53L0X via I2C (SDA=21, SCL=22)
    adafruit/Adafruit BusIO@^1.14.1         ; Dependencia obrigatoria da Adafruit_VL53L0X